### ISSUE TITLE
Dependency on LLVM build dir being up to date

### ISSUE THREAD

**Issue by jasilvanus** [GPUOpen-Drivers/llvm-dialects#13]
When doing a standalone build of `llvm-dialects`, you need to specify the build directory of an `llvm-project` repo.
That `llvm-project` repo must be compatible with the `llvm-dialects` repo, which currently probably just means sufficiently recent.

However, it is not sufficent to check out the correct version of LLVM, but the LLVM build must *also* be up to date.
Otherwise, outdated autogenerated headers are used, resulting in weird errors.

Maybe there is a way to handle this in a better way?

I can think of the following, but there might be other options:

1. Use a standalone build dir for `llvm-dialects` that only depends on the LLVM source and also contains LLVM build artifacts.
2. Trigger an LLVM build as part of the `llvm-dialects` build. This could have unexpected sideeffects though. Maybe rebuild only some parts?

**Comment by Flakebi** [comment]
I think you can already do something like 1. by adding llvm-dialects in LLVM_EXTERNAL_PROJECTS and put it into the right place in the llvm checkout (sorry, no idea where exactly that is, maybe as a subdirectory in `llvm/tools`).
It will then be build as part of LLVM (so the other way around compared to what you described).

Another way to make sure that headers and build artifacts are up-to-date is to build and *install* LLVM, then point the dialects build to the install directory. I didn’t try it, but I guess that may already work with the current cmake config.

**Comment by nhaehnle** [comment]
Yeah, I think there are basically three use scenarios:

1. As an LLVM_EXTERNAL_PROJECT, where llvm-dialects is actually a sub-project of LLVM.
2. Against an installed LLVM.
3. Against an LLVM that is integrated into the same larger build process.

Option 1 is used in LLPC. Option 2 is supposed to work and is what I would use to eventually set up proper testing of llvm-dialects. Option 3 I'm not so sure about.

**Comment by jasilvanus** [comment]
The suggestion to put `llvm-dialects` into `llvm/tools` worked nicely, after a re-cmake the `llvm-dialects` target was available even without declaring it explicitly as `LLVM_EXTERNAL_PROJECT`.

Thanks!
