### ISSUE TITLE
clang warnings "'lock_guard' may not intend to support class template argument deduction"

### ISSUE THREAD

**Issue by trenouf** [GPUOpen-Drivers/llvm-dialects#36]
Hi Nicolai. When building llpc with clang, I get:

```
imported/llvm-dialects/lib/Dialect/Dialect.cpp:66:17: warning: 'lock_guard' may not intend to support class template argument deduction [-Wctad-maybe-unsupported]
```

and the same at lines 76, 88, 98, 106.

My llvm-dialects is:
```
17aafec Add -no-memory-effects option
```
and my llvm-project is:
```
ca5b119ae6bf Merged main:42f957f55d3b into amd-gfx:8516ad1b9031
```
(from the GPUOpen llvm-project).

**Comment by nhaehnle** [comment]
This is annoying because I'm pretty sure the C++ standard does intend for lock_guard to support CTAD, so it's arguably a compiler / standard library implementation bug. Oh well.
